mod handle_errors;

fn main() {
    handle_errors::handle_errors();
}
